name: Backend CI/CD

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:

  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/backend-img:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/backend-img:latest


  deploy-on-device:
    runs-on: self-hosted

    steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Deploy to Kubernetes
          run: |
            cd "/home/hussein-maher/Desktop/Lx/apptraining-2"

            minikube delete
            minikube start --driver=docker
            kubectl apply -f app.yaml

        - name: Wait for frontend pod to be ready
          run: |
              kubectl wait --for=condition=ready pod -l app=frontend --timeout=120s

        - name: Wait for backend pod to be ready
          run: |
            kubectl wait --for=condition=ready pod -l app=backend --timeout=120s

        - name: Wait for postgres pod to be ready
          run: |
            kubectl wait --for=condition=ready pod -l app=postgres --timeout=120s

        - name: Post-deployment actions
          run: |
            echo "All pods are up and running. Proceeding with the next steps."



        - name: port forward front
          run: |
            cd "/home/hussein-maher/Desktop/Lx/apptraining-2"
            kubectl port-forward svc/frontend 3001:3001

        - name: port forward back
          run: |
            cd "/home/hussein-maher/Desktop/Lx/apptraining-2"
            kubectl port-forward svc/backend 3002:3002

        - name: port forward postgres
          run: |
            cd "/home/hussein-maher/Desktop/Lx/apptraining-2"
            kubectl port-forward svc/postgres 5432:5432




        - name: get database
          run: |
            cd "/home/hussein-maher/Desktop/Lx/apptraining-2"
            kubectl exec -i $(kubectl get pods -l app=postgres -o name) -- psql -U admin -d taskapp < init.sql


        - name: run frontend Service 
          run: |
            cd "/home/hussein-maher/Desktop/Lx/apptraining-2"
            minikube service frontend --url




