name: Backend CI/CD

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:

  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/backend-img:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/backend-img:latest

deploy-on-device:
  runs-on: self-hosted

  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to Kubernetes and wait for pods
      run: |
        cd "/home/hussein-maher/Desktop/Lx/apptraining-2"

        minikube start --driver=docker
        kubectl apply -f app.yaml

        echo "Waiting for pods to be ready..."
        kubectl wait --for=condition=ready pod -l app=frontend --timeout=300s
        kubectl wait --for=condition=ready pod -l app=backend --timeout=300s
        kubectl wait --for=condition=ready pod -l app=postgres --timeout=300s

        echo "All pods are ready!"

        echo "Port forwarding frontend, backend, and postgres in background..."
        kubectl port-forward svc/frontend 3001:3001 &
        kubectl port-forward svc/backend 3002:3002 &
        kubectl port-forward svc/postgres 5432:5432 &

    - name: Initialize database
      run: |
        cd "/home/hussein-maher/Desktop/Lx/apptraining-2"
        kubectl exec -i $(kubectl get pods -l app=postgres -o name) -- psql -U admin -d taskapp < init.sql

    - name: Get frontend URL
      run: |
        cd "/home/hussein-maher/Desktop/Lx/apptraining-2"
        minikube service frontend --url
